apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  annotations:
    prometheus.io/path: /prometheus/metrics
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
